<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj" />
    <Compile Include="../osu.Web/Storage/BrowserSettingsStore.cs" Link="BrowserSettingsStore.cs" />
  </ItemGroup>
</Project>
